spring:
  application:
    name: discodeit
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          service-base-url: http://localhost:80
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discode1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    com:
      sprint:
        mission:
          discodeit: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE


