spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discode1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
 #   show-sql: true

logging:
  level:
    org.springframework: INFO

discodeit:
  storage:
    type: local
    local:
      root-path: ./discodeit/storage

