
spring:
  application:
    name: discodeit
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}
  datasource:
    url: jdbc:postgresql://db:5432/discodeit
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

logging:
  level:
    com:
      sprint:
        mission:
          discodeit: INFO
    org:
      hibernate:
        SQL: INFO

discodeit:
  storage:
    type: local
    local:
      root-path: ./discodeit/local/storage/prod
