spring:
  profiles:
    active: prod
  info:
    app:
      name: Discodeit
      version: 1.7.0
    java:
      version: 17
    spring:
      boot:
        version: 3.5.0
    config:
      datasource:
        url: jdbc:postgresql://localhost:5432/discodeit
        username: discodeit_user
        password: discode1234
        driver-class-name: org.postgresql.Driver
      jpa:
        ddl-auto: none
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB

logging:
  level:
    root: INFO

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: never
    info:
      enabled: true
    metrics:
      enabled: true
    loggers:
      enabled: true

discodeit:
  storage:
    type: ${STORAGE_TYPE:local} # 기본 값 local
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discoedit/storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # 기본값 10분
    path: ./discodeit/local/storage
